var BlueBuilding =  {
	"m_name"				:			"BlueBuilding",
	"m_synnextlogo"         :           "Skins/BlueBuilding/logo.png",         
	"m_background"          :           "Skins/BlueBuilding/building.jpg"           ,        
	"m_radius"       :           2                              ,        
	"m_buttongradient1"     :           "#7EA1C9"                       ,         
	"m_buttongradient2"     :           "#779bc6"                       ,         
	"m_buttonopacity"       :           1                               ,         
	"m_clickbuttongradient1":           "#b0c2d7"                       ,         
	"m_clickbuttongradient2":           "#b0c2d7"                       ,         
	"m_clickbuttonopacity"  :           1                               ,         
	"m_tablecolortitle"     :           "#b4bdc0"                       ,         
	"m_tableopacitytitle"   :           1                               ,         
	"m_tablecolorline1"     :           "#EBEDEF"                       ,         
	"m_tableopacityline1"   :           1                               ,         
	"m_tablecolorline2"     :           "#D5D5D5"                       ,         
	"m_tableopacityline2"   :           1                               ,         
	"m_fastlinkingcolor"    :           "#779bc6"                        ,        
	"m_fastlinkingopacity"  :           1                               ,         
	"m_intelliboxcolor"     :           "#779bc6"                       ,         
	"m_intelliboxopacity"   :           1                               ,         
	"m_menuboxcolor"        :           "#EBEDEF"                       ,         
	"m_menuboxopacity"      :           0.93                            ,         
	"m_tabbedmenuboxcolor"  :           "#EBEDEF"                       ,         
	"m_tabbedmenuboxopacity":           0.93                            ,         
	"m_titlecolor"          :           "#1E1E1E"                       ,         
	"m_popupcolor"          :           "#D5D5D5"                       ,         
	"m_popupopacity"        :           1                               ,         
	"m_inactivetabcolor"    :           "#779bc6"                       ,         
	"m_inactivefontcolor"   :           "#c9c7bf"                       ,         
	"m_listbackgroundcolor" :           "#a6bbd3"                       ,         
	"m_suggestbubbleimage"  :           "Skins/BlueBuilding/suggestionbubble.png",         
	"m_suggestbubbleopacity":           0.7                             ,         
	"m_tooltipcolor"        :           "#a3bcd8"                       ,         
	"m_bordersize"          :           1                               ,         
    "m_bordercolor"         :           "#254b72"                       ,
	"m_usedfont"            :           "Arial"                         ,         
	"m_warningcolor"        :           "#6400BC"                       ,         
	"m_selectcolor"         :           "#ffffff"                       ,         
	"m_lockedinputcolor"    :           "#a6bbd3"                       ,         
    "m_titlefontsize"		:		      14                            ,
    "m_textfontsize"		:		      12                             ,
    "m_editBackgroundColor"	:		    "#741E3A"    ,
    "m_activetabfontcolor"  :           "#1E1E1E",
    "m_inputboxbackground"  :           "#BFD0E4",
    "m_confirmationbuttongradient1"             :   "#66B22D",
    "m_confirmationbuttongradient2"             :   "#66B22D",
    "m_confirmationbuttonopacity"               :   1,
    "m_clickconfirmationbuttongradient1"        :   "#5EA12A",
    "m_clickconfirmationbuttongradient2"        :   "#5EA12A",
    "m_clickconfirmationbuttonopacity"          :   1,
    "m_exitbuttoncolor"                         :   "transparent",
    "m_exitbuttonhovercolor"                    :   "#E83C3B",
    "m_tableselectentrycolor"                   :   "#ffffff",
    "m_switchcoloronactivated"                  :   "#779bc6",
    "m_switchcolorondeactivated"                :   "#E6E6E6",
    "m_switchhandlecolor"                       :   "#FFFFFF",
    "m_switchboxradius"                         :   0,
    "m_switchhandleradius"                      :   0,
    "m_skinpreviewnamebaropacity"               :   1,
    "m_skinpreviewnamebarcolor"                 :   "#779bc6",
    "m_skinpreviewnamebarfontcolor"             :   "#FFFFFF",
    "m_skinpreviewbackgroundselectionmarkcolor" :   "#779bc6",
    "m_skinpreviewbackgroundselectionmarkwidth" :   5,
    "m_thumbnailcontainercolor"                  :   "transparent",
    "m_highlightingtextmouseoveropacity"        :   0.4,
    "m_highlightingtextmargin"                  :   10,
    "m_highlightingtextbackgroundcolor"     :   "#ffffff",
    "m_buttonhovergradient1"                    :   "#779bc6",
    "m_buttonhovergradient2"                    :   "#b0c2d7",
    "m_bannermodeiconrectanglebordercolor"      :   "white",
    "m_bannermodeiconrectangleborderwidth"      :   3,
    "m_bannermodeiconrectanglecolor"            :   "#779bc6",
    "m_bannermodeiconrectanglecolorhighlight"   :   "#b0c2d7",
    "m_bannermodetextrectanglecolorhighlight"   :   "#E6E6E6",
    "m_bannermodetextalignment"                 :   4,          // 1 (Align Left), 2 (Align Right), 4 (AlignHCenter), 8 (Align Justify), 32 (AlignTop), 64 (Align Bottom), 128 (AlignVCenter)
    "m_confirmationbuttonhovergradient1"        :   "#5EA12A",
    "m_confirmationbuttonhovergradient2"        :   "#5EA12A",
    "m_radiocheckboxcolor"                      :   "#E6E6E6",
    "m_textcolor"                               :   "#000000",
    "m_textcolorhighlight"                      :   "#FFFFFF",
    "m_iconcolor"                               :   "#000000",
    "m_iconcolorhighlight"                      :   "#FFFFFF",
    "m_welcomeboxelementiconcolor"              :   "#1E1E1E",
    "m_welcomeboxelementiconcolorbannermode"    :   "#FFFFFF",
    "m_buttontextcolor"                         :   "#FFFFFF",
    "m_confirmationbuttontextcolor"             :   "#FFFFFF",
    "m_menuelementleftbordercolor"              :   "#FFFFFF",
    "m_menuelementleftborderwidth"              :   0,
    "m_presentationlogo"                        :   "Skins/Universe/Logoexample.png",
    "m_tablecolortitletext"                     :   "#FFFFFF",
    "m_calenderplaceholderdatescolor"           :   "#848484",
    "m_calenderselecteddatecolor"               :   "#FFFFFF",
    "m_calenderdatesofselectedmonthcolor"       :   "#000000",
    "m_calenderbarofselectedmonthcolor"         :   "#779bc6",
    "m_icononbackgroundcolor"                   :   "#FFFFFF",
    "m_calenderdatebackgroundcolor"             :   "transparent",
    "m_calenderselecteddatebackgroundcolor"     :   "#779bc6",
    "m_grouptitlecolor"                         :   "#1E1E1E",
    "m_calendarcolor"                           :   "#EBEDEF",
    "m_calendaropacity"                         :   0.93,
    "m_calendarbordersize"                      :   1,
    "m_calendarbordercolor"                     :   "#254b72",
    "m_cancelbuttongradient1"                   :   "#E83C3B",
    "m_cancelbuttongradient2"                   :   "#E83C3B",
    "m_clickcancelbuttongradient1"              :   "#b71515",
    "m_clickcancelbuttongradient2"              :   "#b71515",
    "m_cancelbuttonhovergradient1"              :   "#d71919",
    "m_cancelbuttonhovergradient2"              :   "#d71919",
    "m_calendarweeknumbercolor"                 :   "#848484",
    "m_radiocheckboxcolorselected"              :   "#7EA1C9",
    "m_radiocontainerlabelboxcolor"             :   "#EBEDEF",
    "m_standaloneiconcolor"                     :   "#000000",
    "m_standaloneiconcolorhighlight"            :   "#779bc6",
    "m_iconbackgroundhovercolor"                :   "#779bc6",
    "m_filechooserdotscolor"                    :   "grey",
    "m_popuptopbarcolor"                        :   "transparent",
    "m_inputboxtextcolor"                       :   "grey",
    "m_inputboxhighlightedtextcolor"            :   "#7EA1C9",
    "m_inputboxselectedtextcolor"               :   "black",
    "m_inputboxtypedtextcolor"                  :   "black",
    "m_inputboxsmalltextcolor"                  :   "grey",
    "m_thumbnailcontainertextcolor"             :   "grey",
    "m_thumbnailcontainersmalltextcolor"        :   "grey",
    "m_linkcolor"                               :   "#254b72"
}
