var Universe =  {
    "m_name"				:		"Universe",
    "m_synnextlogo"         :        "Skins/Universe/logo.png",
    "m_background"          :        "Skins/Universe/backgroundgalaxy.jpg",
    "m_radius"       :        0,
    "m_buttongradient1"     :        "#2979EF",
    "m_buttongradient2"     :        "#2979EF",
	"m_buttonopacity"       :        1,
    "m_clickbuttongradient1":        "#0835FF",
    "m_clickbuttongradient2":        "#0835FF",
	"m_clickbuttonopacity"  :        1,
    "m_tablecolortitle"     :        "#2979EF",
	"m_tableopacitytitle"   :        1,
    "m_tablecolorline1"     :        "#E6E6E6",
	"m_tableopacityline1"   :        1,
    "m_tablecolorline2"     :        "#FFFFFF",
	"m_tableopacityline2"   :        1,
    "m_fastlinkingcolor"    :        "#FF0000",
	"m_fastlinkingopacity"  :        1,
    "m_intelliboxcolor"     :        "#2979EF",
	"m_intelliboxopacity"   :        1,
        "m_menuboxcolor"        :    "#FFFFFF",
    "m_menuboxopacity"      :        1,
    "m_tabbedmenuboxcolor"  :        "#FFFFFF",
    "m_tabbedmenuboxopacity":        1,
    "m_titlecolor"          :        "#000000",
    "m_popupcolor"          :        "#FFFFFF",
	"m_popupopacity"        :        1,
        "m_inactivetabcolor"    :    "#2979EF",
    "m_inactivefontcolor"   :        "#FFFFFF",
    "m_listbackgroundcolor" :        "#FF0000",
    "m_suggestbubbleimage"  :        "Skins/Universe/suggestionbubble.png",
    "m_suggestbubbleopacity":        1,
    "m_tooltipcolor"        :        "#FF0000",
    "m_bordersize"          :        0,
    "m_bordercolor"         :        "#FFFFFF",
	"m_usedfont"            :        "Arial",
    "m_warningcolor"        :        "#FF0000",
    "m_selectcolor"         :        "#c1d8fa",//"#508FED",
    "m_lockedinputcolor"    :        "#c1d8fa",
    "m_titlefontsize"		:	     14,
    "m_textfontsize"		:        13,
    "m_editBackgroundColor"	:	     "#FF651E",
    "m_activetabfontcolor"  :        "#000000",
    "m_inputboxbackground"  :        "#E6E6E6",
    //added
    "m_confirmationbuttongradient1"             :   "#66B22D",
    "m_confirmationbuttongradient2"             :   "#66B22D",
    "m_confirmationbuttonopacity"               :   1,
    "m_clickconfirmationbuttongradient1"        :   "#5EA12A",
    "m_clickconfirmationbuttongradient2"        :   "#5EA12A",
    "m_clickconfirmationbuttonopacity"          :   1,
    "m_exitbuttoncolor"                         :   "transparent",
    "m_exitbuttonhovercolor"                    :   "#E83C3B",
    "m_tableselectentrycolor"                   :   "#9bc0f8",
    "m_switchcoloronactivated"                  :   "#8BC63F",
    "m_switchcolorondeactivated"                :   "#E6E6E6",
    "m_switchhandlecolor"                       :   "#FFFFFF",
    "m_switchboxradius"                         :   20,
    "m_switchhandleradius"                      :   20,
    "m_skinpreviewnamebaropacity"               :   1,
    "m_skinpreviewnamebarcolor"                 :   "#2979EF",
    "m_skinpreviewnamebarfontcolor"             :   "#FFFFFF",
    "m_skinpreviewbackgroundselectionmarkcolor" :   "#2979EF",
    "m_skinpreviewbackgroundselectionmarkwidth" :   5,
    "m_thumbnailcontainercolor"                  :   "#E6E6E6",
    "m_highlightingtextmouseoveropacity"        :   0.2,
    "m_highlightingtextmargin"                  :   0,
    "m_highlightingtextbackgroundcolor"     :   "#508FED",
    "m_buttonhovergradient1"                    :   "#0835FF",
    "m_buttonhovergradient2"                    :   "#0835FF",
    "m_bannermodeiconrectanglebordercolor"      :   "white",
    "m_bannermodeiconrectangleborderwidth"      :   0,
    "m_bannermodeiconrectanglecolor"            :   "#2979EF",
    "m_bannermodeiconrectanglecolorhighlight"   :   "#151B54",
    "m_bannermodetextrectanglecolorhighlight"   :   "#E6E6E6",
    "m_confirmationbuttonhovergradient1"        :   "#5EA12A",
    "m_confirmationbuttonhovergradient2"        :   "#5EA12A",
    "m_radiocheckboxcolor"                      :   "#d6d6d6",
    "m_bannermodetextalignment"                 :   4,        // 1 (Align Left), 2 (Align Right), 4 (AlignHCenter), 8 (Align Justify), 32 (AlignTop), 64 (Align Bottom), 128 (AlignVCenter)
    "m_textcolor"                               :   "#000000",//of mouse a (table)
    "m_textcolorhighlight"                      :   "#FFFFFF",//of mouse a (table)
    "m_iconcolor"                               :   "#000000",//filechooser black and blue icon color
    "m_iconcolorhighlight"                      :   "#FFFFFF",
    "m_welcomeboxelementiconcolor"              :   "#000000",
    "m_welcomeboxelementiconcolorbannermode"    :   "#FFFFFF",
    "m_buttontextcolor"                         :   "#FFFFFF",//color for text of internal button
    "m_confirmationbuttontextcolor"             :   "#FFFFFF", //color for text of confirmaiton button
    "m_menuelementleftbordercolor"              :   "#FFFFFF",
    "m_menuelementleftborderwidth"              :   10,
    "m_presentationlogo"                        :   "Skins/Universe/Logoexample.png",
    "m_tablecolortitletext"                     :   "#FFFFFF",
    "m_calenderplaceholderdatescolor"           :   "#848484",
    "m_calenderselecteddatecolor"               :   "#FFFFFF",
    "m_calenderdatesofselectedmonthcolor"       :   "#000000",
    "m_calenderbarofselectedmonthcolor"         :   "#E73C3B",
    "m_icononbackgroundcolor"                   :   "#FFFFFF", //Like Properties icon
    "m_calenderdatebackgroundcolor"             :   "transparent",
    "m_calenderselecteddatebackgroundcolor"     :   "#2979EF",
    "m_grouptitlecolor"                         :   "#000000",
    "m_calendarcolor"                           :   "#2979EF",
    "m_calendaropacity"                         :   0.93,
    "m_calendarbordersize"                      :   1,
    "m_calendarbordercolor"                     :   "#FFFFFF",
    "m_cancelbuttongradient1"                   :   "#E83C3B",
    "m_cancelbuttongradient2"                   :   "#E83C3B",
    "m_clickcancelbuttongradient1"              :   "#b71515",
    "m_clickcancelbuttongradient2"              :   "#b71515",
    "m_cancelbuttonhovergradient1"              :   "#d71919",
    "m_cancelbuttonhovergradient2"              :   "#d71919",
    "m_calendarweeknumbercolor"                 :   "#848484",
    "m_radiocheckboxcolorselected"              :   "#2979EF",
    "m_radiocontainerlabelboxcolor"             :   "#FFFFFF",
    "m_standaloneiconcolor"                     :   "#000000",
    "m_standaloneiconcolorhighlight"            :   "#2979EF",
    "m_iconbackgroundhovercolor"                :   "#2979EF",
    "m_filechooserdotscolor"                    :   "grey",
    "m_popuptopbarcolor"                        :   "#dedede",
    "m_inputboxtextcolor"                       :   "grey",
    "m_inputboxhighlightedtextcolor"            :   "#2979EF",
    "m_inputboxselectedtextcolor"               :   "black",
    "m_inputboxtypedtextcolor"                  :   "black",
    "m_inputboxsmalltextcolor"                  :   "grey",
    "m_thumbnailcontainertextcolor"             :   "grey",
    "m_thumbnailcontainersmalltextcolor"        :   "grey",
    "m_linkcolor"                               :   "#000000"


}
